# Generated by Django 2.0.6 on 2018-07-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
