# Generated by Django 2.0.6 on 2018-07-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20180721_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueScan',
            fields=[
                ('unique_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Testuser')),
            ],
        ),
    ]
