# Generated by Django 2.0.6 on 2018-07-21 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20180722_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquescan',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Testuser'),
        ),
    ]
